// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {".?AVtype_info@@", 0ULL, "class"},
    {"Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase>", 112ULL, "allocation-size-evidence"},
    {"Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>", 32ULL, "allocation-size-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {".?AVtype_info@@", ".?AVtype_info@@", -1LL, false, "msvc-rtti-base-class-descriptor", "certain"},
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const CRefObj<class CThemeMenuBar>::`vftable'", 0x68070U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CSection::`vftable'", 0x68118U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CDataSection::`vftable'", 0x68120U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CPaintBuffer::`vftable'", 0x68128U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CLinearFadeAnimation::`vftable'", 0x68168U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefObj<class CThemeMenuMetrics>::`vftable'", 0x68188U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRevertImpersonation::`vftable'", 0x68560U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::`vftable'", 0x68AC0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const ImmersiveColorTelemetry::`vftable'", 0x68FB8U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::details::FeatureLogging::`vftable'", 0x68FD8U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::TraceLoggingProvider::`vftable'", 0x6DDF0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CPaintBufferAnimation::`vftable'", 0x6DE10U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CThemeMemStream::`vftable'", 0x6DE30U, 14U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CThemeLoader::`vftable'", 0x6DEA0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const ThemesLogging::`vftable'", 0x6DEC8U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wistd::__function::__base<bool __cdecl (void *, uint64_t, void *, uint64_t, unsigned int)>::`vftable'", 0x6DEE8U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const type_info::`vftable'", 0x6DF18U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::ResultException::`vftable'", 0x6DF30U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::exception::`vftable'", 0x6DF40U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CCubicFadeAnimation::`vftable'", 0x6DF50U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::Details::DefaultModule<1>::`vftable'", 0x6DF70U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::`vftable'{for `Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory'}", 0x6DFD0U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<13>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil>'}", 0x6E008U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescriptionFactory::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<13>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil>'}", 0x6E050U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::`vftable'", 0x6E098U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescriptionFactory::`vftable'", 0x6E0D8U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescriptionFactory::`vftable'{for `Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory'}", 0x6E118U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>::`vftable'", 0x6E150U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::Details::WeakReferenceImpl::`vftable'", 0x6E178U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>::`vftable'", 0x6E1A0U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>::`vftable'", 0x6E1D8U, 10U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>::`vftable'", 0x6E228U, 10U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::`vftable'{for `IWeakReferenceSource'}", 0x6E278U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E298U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>'}", 0x6E2E0U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::`vftable'", 0x6E338U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E378U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::`vftable'{for `IWeakReferenceSource'}", 0x6E3C0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase>::`vftable'", 0x6E3E0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6E400U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase>::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6E460U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E4C0U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::`vftable'{for `IWeakReferenceSource'}", 0x6E508U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>'}", 0x6E528U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6E568U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E5C8U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>'}", 0x6E610U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E648U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>'}", 0x6E690U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct IWeakReferenceSource, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>'}", 0x6E6E8U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `IWeakReferenceSource'}", 0x6E708U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E728U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E770U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::`vftable'", 0x6E7B8U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::`vftable'", 0x6E810U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<1>, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::`vftable'{for `IWeakReferenceSource'}", 0x6E870U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescription::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E8B8U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescription::`vftable'", 0x6E900U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const AnimationDescription::`vftable'{for `IWeakReferenceSource'}", 0x6E960U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVectorIterator::`vftable'{for `IWeakReferenceSource'}", 0x6E980U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVectorIterator::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6E9A0U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVectorIterator::`vftable'", 0x6E9E8U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVector::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6EA40U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVector::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct IWeakReferenceSource, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>'}", 0x6EA88U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVector::`vftable'{for `Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>'}", 0x6EAA8U, 7U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationVector::`vftable'{for `Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>'}", 0x6EAE0U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTOpacityAnimation::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>'}", 0x6EB38U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTOpacityAnimation::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6EB78U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTOpacityAnimation::`vftable'{for `IWeakReferenceSource'}", 0x6EBC0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTTranslationAnimation::`vftable'", 0x6EBE0U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTOpacityAnimation::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6EC00U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTTranslationAnimation::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6EC60U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTTranslationAnimation::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6ECC0U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTScaleAnimation::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>'}", 0x6ED08U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTScaleAnimation::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6ED60U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTScaleAnimation::`vftable'{for `IWeakReferenceSource'}", 0x6EDA8U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTScaleAnimation::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6EDC8U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::FtmBase::`vftable'", 0x6EE28U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTReferenceFloat::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}", 0x6EE70U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTAnimationBase::`vftable'{for `Windows::UI::Core::AnimationMetrics::IPropertyAnimation'}", 0x6EEB8U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTReferenceFloat::`vftable'", 0x6EF10U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const WinRTReferenceFloat::`vftable'{for `IWeakReferenceSource'}", 0x6EF50U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CRefObj<class CThemeMenuPopup>::`vftable'", 0x6EF70U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const CThemeSignature::`vftable'", 0x6EF98U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const VSENUMSYMBOL::`vftable'", 0x6EFA0U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0x68070U, 0U, 0x47970U, "?AddRef@?$CRefObj@VCThemeMenuBar@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuBar>::AddRef(void)", false, 0},
    {0x68070U, 1U, 0x46D90U, "?Release@?$CRefObj@VCThemeMenuBar@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuBar>::Release(void)", false, 0},
    {0x68070U, 2U, 0x3D850U, nullptr, nullptr, true, 0},
    {0x68070U, 3U, 0x3D4A0U, nullptr, nullptr, true, 0},
    {0x68070U, 4U, 0x3D060U, nullptr, nullptr, true, 0},
    {0x68118U, 0U, 0x60700U, nullptr, nullptr, true, 0},
    {0x68120U, 0U, 0x606B0U, nullptr, nullptr, true, 0},
    {0x68128U, 0U, 0x44EE0U, "?GetTargetDC@CPaintBuffer@@UEBAPEAUHDC__@@XZ", "public: virtual struct HDC__* __cdecl CPaintBuffer::GetTargetDC(void) const", false, 0},
    {0x68128U, 1U, 0x54080U, "?GetTargetRect@CPaintBuffer@@UEBAJPEAUtagRECT@@@Z", "public: virtual long __cdecl CPaintBuffer::GetTargetRect(struct tagRECT *) const", false, 0},
    {0x68128U, 2U, 0x45030U, "?GetDC@CPaintBuffer@@UEBAPEAUHDC__@@XZ", "public: virtual struct HDC__* __cdecl CPaintBuffer::GetDC(void) const", false, 0},
    {0x68128U, 3U, 0x37FD0U, "?GetBits@CPaintBuffer@@UEBAJPEAPEAUtagRGBQUAD@@PEAH@Z", "public: virtual long __cdecl CPaintBuffer::GetBits(struct tagRGBQUAD * *, int *) const", false, 0},
    {0x68128U, 4U, 0x1A380U, "?Clear@CPaintBuffer@@UEAAJPEBUtagRECT@@@Z", "public: virtual long __cdecl CPaintBuffer::Clear(struct tagRECT const *)", false, 0},
    {0x68128U, 5U, 0x2BF20U, "?SetAlpha@CPaintBuffer@@UEAAJPEBUtagRECT@@E@Z", "public: virtual long __cdecl CPaintBuffer::SetAlpha(struct tagRECT const *, unsigned char)", false, 0},
    {0x68128U, 6U, 0x54060U, "?GetBitsPerPixel@CPaintBuffer@@UEBAKXZ", "public: virtual unsigned long __cdecl CPaintBuffer::GetBitsPerPixel(void) const", false, 0},
    {0x68128U, 7U, 0x42DB0U, "?GetBitmapDpiScaleValue@CPaintBuffer@@UEBAJXZ", "public: virtual long __cdecl CPaintBuffer::GetBitmapDpiScaleValue(void) const", false, 0},
    {0x68168U, 0U, 0x412F0U, nullptr, nullptr, true, 0},
    {0x68168U, 1U, 0x54100U, nullptr, nullptr, true, 0},
    {0x68168U, 2U, 0x48CF0U, nullptr, nullptr, true, 0},
    {0x68168U, 3U, 0x47FA0U, nullptr, nullptr, true, 0},
    {0x68188U, 0U, 0x47E70U, "?AddRef@?$CRefObj@VCThemeMenuMetrics@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuMetrics>::AddRef(void)", false, 0},
    {0x68188U, 1U, 0x256A0U, "?Release@?$CRefObj@VCThemeMenuMetrics@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuMetrics>::Release(void)", false, 0},
    {0x68560U, 0U, 0x56C20U, nullptr, nullptr, true, 0},
    {0x68AC0U, 0U, 0x51830U, nullptr, nullptr, true, 0},
    {0x68AC0U, 1U, 0x53570U, nullptr, nullptr, true, 0},
    {0x68AC0U, 2U, 0x53570U, nullptr, nullptr, true, 0},
    {0x68AC0U, 3U, 0x49600U, "?destroy@?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAAXXZ", "public: virtual void __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::destroy(void)", false, 0},
    {0x68AC0U, 4U, 0x327C0U, "??R?$__func@V<lambda_8db0ce862824541f40dfb767113f1e28>@@$$A6A_NPEAX_K01I@Z@__function@wistd@@UEAA_N$$QEAPEAX$$QEA_K01$$QEAI@Z", "public: virtual bool __cdecl wistd::__function::__func<class <lambda_8db0ce862824541f40dfb767113f1e28>, bool __cdecl (void *, uint64_t, class <lambda_8db0ce862824541f40dfb767113f1e28>, void *, unsigned int)>::operator()(void * &&, uint64_t &&, void * &&, uint64_t &&, unsigned int &&)", false, 0},
    {0x68FB8U, 0U, 0x52840U, nullptr, nullptr, true, 0},
    {0x68FB8U, 1U, 0x49600U, nullptr, nullptr, true, 0},
    {0x68FB8U, 2U, 0x52880U, nullptr, nullptr, true, 0},
    {0x68FB8U, 3U, 0x42AA0U, nullptr, nullptr, true, 0},
    {0x68FD8U, 0U, 0x52840U, nullptr, nullptr, true, 0},
    {0x68FD8U, 1U, 0x49600U, nullptr, nullptr, true, 0},
    {0x68FD8U, 2U, 0x52880U, nullptr, nullptr, true, 0},
    {0x68FD8U, 3U, 0x42AE0U, nullptr, nullptr, true, 0},
    {0x6DDF0U, 0U, 0x52840U, "?NotifyFailure@TraceLoggingProvider@wil@@EEAA_NAEBUFailureInfo@2@@Z", "private: virtual bool __cdecl wil::TraceLoggingProvider::NotifyFailure(struct wil::FailureInfo const &)", false, 0},
    {0x6DDF0U, 1U, 0x49600U, "?Initialize@TraceLoggingProvider@wil@@MEAAXXZ", "protected: virtual void __cdecl wil::TraceLoggingProvider::Initialize(void)", false, 0},
    {0x6DDF0U, 2U, 0x52880U, "?OnErrorReported@TraceLoggingProvider@wil@@MEAAX_NAEBUFailureInfo@2@@Z", "protected: virtual void __cdecl wil::TraceLoggingProvider::OnErrorReported(bool, struct wil::FailureInfo const &)", false, 0},
    {0x6DDF0U, 3U, 0x518B0U, nullptr, nullptr, true, 0},
    {0x6DE10U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DE10U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DE10U, 2U, 0x48CF0U, nullptr, nullptr, true, 0},
    {0x6DE10U, 3U, 0x47FC0U, "?Initialize@CPaintBufferAnimation@@MEAAJPEAUHWND__@@AEBU_BP_ANIMATIONPARAMS@@@Z", "protected: virtual long __cdecl CPaintBufferAnimation::Initialize(struct HWND__*, struct _BP_ANIMATIONPARAMS const &)", false, 0},
    {0x6DE30U, 0U, 0x47230U, "?QueryInterface@CThemeMemStream@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl CThemeMemStream::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6DE30U, 1U, 0x47E30U, "?AddRef@CThemeMemStream@@UEAAKXZ", "public: virtual unsigned long __cdecl CThemeMemStream::AddRef(void)", false, 0},
    {0x6DE30U, 2U, 0x49EE0U, "?Release@CThemeMemStream@@UEAAKXZ", "public: virtual unsigned long __cdecl CThemeMemStream::Release(void)", false, 0},
    {0x6DE30U, 3U, 0x61520U, "?Read@CThemeMemStream@@UEAAJPEAXKPEAK@Z", "public: virtual long __cdecl CThemeMemStream::Read(void *, unsigned long, unsigned long *)", false, 0},
    {0x6DE30U, 4U, 0x36940U, "?Write@CThemeMemStream@@UEAAJPEBXKPEAK@Z", "public: virtual long __cdecl CThemeMemStream::Write(void const *, unsigned long, unsigned long *)", false, 0},
    {0x6DE30U, 5U, 0x3BB40U, "?Seek@CThemeMemStream@@UEAAJT_LARGE_INTEGER@@KPEAT_ULARGE_INTEGER@@@Z", "public: virtual long __cdecl CThemeMemStream::Seek(union _LARGE_INTEGER, unsigned long, union _ULARGE_INTEGER *)", false, 0},
    {0x6DE30U, 6U, 0x615C0U, "?SetSize@CThemeMemStream@@UEAAJT_ULARGE_INTEGER@@@Z", "public: virtual long __cdecl CThemeMemStream::SetSize(union _ULARGE_INTEGER)", false, 0},
    {0x6DE30U, 7U, 0x61510U, nullptr, nullptr, true, 0},
    {0x6DE30U, 8U, 0x54100U, "?Commit@CThemeMemStream@@UEAAJK@Z", "public: virtual long __cdecl CThemeMemStream::Commit(unsigned long)", false, 0},
    {0x6DE30U, 9U, 0x61510U, nullptr, nullptr, true, 0},
    {0x6DE30U, 10U, 0x61510U, nullptr, nullptr, true, 0},
    {0x6DE30U, 11U, 0x61510U, nullptr, nullptr, true, 0},
    {0x6DE30U, 12U, 0x61660U, "?Stat@CThemeMemStream@@UEAAJPEAUtagSTATSTG@@K@Z", "public: virtual long __cdecl CThemeMemStream::Stat(struct tagSTATSTG *, unsigned long)", false, 0},
    {0x6DE30U, 13U, 0x61510U, nullptr, nullptr, true, 0},
    {0x6DEA0U, 0U, 0x23770U, "?AddIndex@CThemeLoader@@UEAAJPEBG0HHHH@Z", "public: virtual long __cdecl CThemeLoader::AddIndex(unsigned short const *, unsigned short const *, int, int, int, int)", false, 0},
    {0x6DEA0U, 1U, 0x36FA0U, "?AddData@CThemeLoader@@UEAAJFEPEBXK@Z", "public: virtual long __cdecl CThemeLoader::AddData(short, unsigned char, void const *, unsigned long)", false, 0},
    {0x6DEA0U, 2U, 0x46230U, "?GetNextDataIndex@CThemeLoader@@UEAAHXZ", "public: virtual int __cdecl CThemeLoader::GetNextDataIndex(void)", false, 0},
    {0x6DEA0U, 3U, 0x241D0U, "?AddToDIBDataArray@CThemeLoader@@UEAAHPEAXFF@Z", "public: virtual int __cdecl CThemeLoader::AddToDIBDataArray(void *, short, short)", false, 0},
    {0x6DEA0U, 4U, 0x25590U, "?AddBaseClass@CThemeLoader@@UEAAJHH@Z", "public: virtual long __cdecl CThemeLoader::AddBaseClass(int, int)", false, 0},
    {0x6DEC8U, 0U, 0x52840U, nullptr, nullptr, true, 0},
    {0x6DEC8U, 1U, 0x49600U, nullptr, nullptr, true, 0},
    {0x6DEC8U, 2U, 0x52880U, nullptr, nullptr, true, 0},
    {0x6DEC8U, 3U, 0x60AF0U, nullptr, nullptr, true, 0},
    {0x6DEE8U, 0U, 0x517F0U, nullptr, nullptr, true, 0},
    {0x6DEE8U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DEE8U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DEE8U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DEE8U, 4U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6DF18U, 0U, 0x501F0U, nullptr, nullptr, true, 0},
    {0x6DF30U, 0U, 0x51870U, nullptr, nullptr, true, 0},
    {0x6DF30U, 1U, 0x53700U, "?what@ResultException@wil@@UEBAPEBDXZ", "public: virtual char const * __cdecl wil::ResultException::what(void) const", false, 0},
    {0x6DF40U, 0U, 0x518F0U, nullptr, nullptr, true, 0},
    {0x6DF40U, 1U, 0x53860U, "?what@exception@std@@UEBAPEBDXZ", "public: virtual char const * __cdecl std::exception::what(void) const", false, 0},
    {0x6DF50U, 0U, 0x412F0U, nullptr, nullptr, true, 0},
    {0x6DF50U, 1U, 0x54100U, nullptr, nullptr, true, 0},
    {0x6DF50U, 2U, 0x498F0U, nullptr, nullptr, true, 0},
    {0x6DF50U, 3U, 0x47FA0U, nullptr, nullptr, true, 0},
    {0x6DF70U, 0U, 0x54530U, nullptr, nullptr, true, 0},
    {0x6DF70U, 1U, 0x54790U, "?IncrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::IncrementObjectCount(void)", false, 0},
    {0x6DF70U, 2U, 0x54570U, "?DecrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::DecrementObjectCount(void)", false, 0},
    {0x6DF70U, 3U, 0x54780U, nullptr, nullptr, true, 0},
    {0x6DF70U, 4U, 0x54740U, nullptr, nullptr, true, 0},
    {0x6DF70U, 5U, 0x54770U, nullptr, nullptr, true, 0},
    {0x6DF70U, 6U, 0x54750U, nullptr, nullptr, true, 0},
    {0x6DF70U, 7U, 0x54760U, nullptr, nullptr, true, 0},
    {0x6DF70U, 8U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6DF70U, 9U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6DF70U, 10U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6DF70U, 11U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 0U, 0x5C5E0U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 1U, 0x5AF30U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 2U, 0x5C9F0U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 3U, 0x5B680U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 4U, 0x5BC50U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 5U, 0x5C010U, nullptr, nullptr, true, 0},
    {0x6DFD0U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E008U, 0U, 0x5C5F0U, nullptr, nullptr, true, 0},
    {0x6E008U, 1U, 0x5AF40U, nullptr, nullptr, true, 0},
    {0x6E008U, 2U, 0x5CA00U, nullptr, nullptr, true, 0},
    {0x6E008U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E008U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E008U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E008U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E008U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E008U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E050U, 0U, 0x5C5F0U, nullptr, nullptr, true, 0},
    {0x6E050U, 1U, 0x5B1A0U, nullptr, nullptr, true, 0},
    {0x6E050U, 2U, 0x5CF00U, nullptr, nullptr, true, 0},
    {0x6E050U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E050U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E050U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E050U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E050U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E050U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E098U, 0U, 0x5C560U, "?QueryInterface@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E098U, 1U, 0x5AEE0U, "?AddRef@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::AddRef(void)", false, 0},
    {0x6E098U, 2U, 0x5C970U, "?Release@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::Release(void)", false, 0},
    {0x6E098U, 3U, 0x5B610U, "?GetIids@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E098U, 4U, 0x5BC20U, "?GetRuntimeClassName@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E098U, 5U, 0x5BFD0U, "?GetTrustLevel@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E098U, 6U, 0x5AEB0U, "?ActivateInstance@?$ActivationFactory@UIAnimationDescriptionFactory@AnimationMetrics@Core@UI@Windows@@VFtmBase@WRL@Microsoft@@VNil@Details@78@$0A@@WRL@Microsoft@@UEAAJPEAPEAUIInspectable@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Windows::UI::Core::AnimationMetrics::IAnimationDescriptionFactory, class Microsoft::WRL::FtmBase, class Microsoft::WRL::Details::Nil, 0>::ActivateInstance(struct IInspectable * *)", false, 0},
    {0x6E098U, 7U, 0x5AB70U, nullptr, nullptr, true, 0},
    {0x6E0D8U, 0U, 0x5C560U, "?QueryInterface@AnimationDescriptionFactory@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl AnimationDescriptionFactory::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E0D8U, 1U, 0x5B180U, "?AddRef@AnimationDescriptionFactory@@UEAAKXZ", "public: virtual unsigned long __cdecl AnimationDescriptionFactory::AddRef(void)", false, 0},
    {0x6E0D8U, 2U, 0x5CEE0U, "?Release@AnimationDescriptionFactory@@UEAAKXZ", "public: virtual unsigned long __cdecl AnimationDescriptionFactory::Release(void)", false, 0},
    {0x6E0D8U, 3U, 0x5B610U, "?GetIids@AnimationDescriptionFactory@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl AnimationDescriptionFactory::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E0D8U, 4U, 0x5BCB0U, "?GetRuntimeClassName@AnimationDescriptionFactory@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl AnimationDescriptionFactory::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E0D8U, 5U, 0x5C040U, "?GetTrustLevel@AnimationDescriptionFactory@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl AnimationDescriptionFactory::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E0D8U, 6U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E0D8U, 7U, 0x5AB70U, nullptr, nullptr, true, 0},
    {0x6E118U, 0U, 0x5C5E0U, nullptr, nullptr, true, 0},
    {0x6E118U, 1U, 0x5B190U, nullptr, nullptr, true, 0},
    {0x6E118U, 2U, 0x5CEF0U, nullptr, nullptr, true, 0},
    {0x6E118U, 3U, 0x5B680U, nullptr, nullptr, true, 0},
    {0x6E118U, 4U, 0x5BCD0U, nullptr, nullptr, true, 0},
    {0x6E118U, 5U, 0x5C050U, nullptr, nullptr, true, 0},
    {0x6E118U, 6U, 0x5B2C0U, "?CreateInstance@AnimationDescriptionFactory@@EEAAJW4AnimationEffect@AnimationMetrics@Core@UI@Windows@@W4AnimationEffectTarget@3456@PEAPEAUIAnimationDescription@3456@@Z", "private: virtual long __cdecl AnimationDescriptionFactory::CreateInstance(enum Windows::UI::Core::AnimationMetrics::AnimationEffect, enum Windows::UI::Core::AnimationMetrics::AnimationEffectTarget, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription * *)", false, 0},
    {0x6E150U, 0U, 0x5C900U, nullptr, nullptr, true, 0},
    {0x6E150U, 1U, 0x5B170U, nullptr, nullptr, true, 0},
    {0x6E150U, 2U, 0x5CE50U, nullptr, nullptr, true, 0},
    {0x6E150U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E150U, 4U, 0x5ACC0U, nullptr, nullptr, true, 0},
    {0x6E178U, 0U, 0x5C900U, nullptr, nullptr, true, 0},
    {0x6E178U, 1U, 0x5B170U, nullptr, nullptr, true, 0},
    {0x6E178U, 2U, 0x5CE50U, nullptr, nullptr, true, 0},
    {0x6E178U, 3U, 0x5D050U, "?Resolve@WeakReferenceImpl@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAUIInspectable@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::WeakReferenceImpl::Resolve(struct _GUID const &, struct IInspectable * *)", false, 0},
    {0x6E178U, 4U, 0x5AD30U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 4U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 5U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1A0U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 4U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 5U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E1D8U, 9U, 0x5BA50U, "?GetMany@?$IVectorView_impl@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@$00@Collections@Foundation@Windows@@UEAAJIIPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@4@PEAI@Z", "public: virtual long __cdecl Windows::Foundation::Collections::IVectorView_impl<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *, 1>::GetMany(unsigned int, unsigned int, struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *, unsigned int *)", false, 0},
    {0x6E228U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 4U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 5U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E228U, 9U, 0x5BA40U, "?GetMany@?$IIterator_impl@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@$00@Collections@Foundation@Windows@@UEAAJIPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@4@PEAI@Z", "public: virtual long __cdecl Windows::Foundation::Collections::IIterator_impl<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *, 1>::GetMany(unsigned int, struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *, unsigned int *)", false, 0},
    {0x6E278U, 0U, 0x5C740U, nullptr, nullptr, true, 0},
    {0x6E278U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6E278U, 2U, 0x5CB50U, nullptr, nullptr, true, 0},
    {0x6E278U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6E298U, 0U, 0x5C750U, nullptr, nullptr, true, 0},
    {0x6E298U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6E298U, 2U, 0x5CB60U, nullptr, nullptr, true, 0},
    {0x6E298U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E298U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E298U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E298U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E298U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E298U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 0U, 0x5C8F0U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 1U, 0x5B160U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 2U, 0x5CE40U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 3U, 0x5BA30U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 4U, 0x5BC70U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 5U, 0x5C030U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 9U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E2E0U, 10U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E338U, 0U, 0x5C6B0U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IReference@M@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E338U, 1U, 0x5AF50U, nullptr, nullptr, true, 0},
    {0x6E338U, 2U, 0x5CAC0U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IReference@M@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::Release(void)", false, 0},
    {0x6E338U, 3U, 0x5B700U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IReference@M@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::IReference<float>, class Microsoft::WRL::FtmBase>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E338U, 4U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E338U, 5U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6E338U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E338U, 7U, 0x5ABC0U, nullptr, nullptr, true, 0},
    {0x6E378U, 0U, 0x5C8D0U, nullptr, nullptr, true, 0},
    {0x6E378U, 1U, 0x5B140U, nullptr, nullptr, true, 0},
    {0x6E378U, 2U, 0x5CE20U, nullptr, nullptr, true, 0},
    {0x6E378U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E378U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E378U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E378U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E378U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E378U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E3C0U, 0U, 0x5C8E0U, nullptr, nullptr, true, 0},
    {0x6E3C0U, 1U, 0x5B150U, nullptr, nullptr, true, 0},
    {0x6E3C0U, 2U, 0x5CE30U, nullptr, nullptr, true, 0},
    {0x6E3C0U, 3U, 0x5C2F0U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::GetWeakReference(struct IWeakReference * *)", false, 0},
    {0x6E3E0U, 0U, 0x5C870U, nullptr, nullptr, true, 0},
    {0x6E3E0U, 1U, 0x5B0D0U, nullptr, nullptr, true, 0},
    {0x6E3E0U, 2U, 0x5CD80U, nullptr, nullptr, true, 0},
    {0x6E3E0U, 3U, 0x5C240U, nullptr, nullptr, true, 0},
    {0x6E400U, 0U, 0x5C8C0U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E400U, 1U, 0x5B0E0U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::AddRef(void)", false, 0},
    {0x6E400U, 2U, 0x5CD90U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::Release(void)", false, 0},
    {0x6E400U, 3U, 0x5B990U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E400U, 4U, 0x5AEB0U, "?GetRuntimeClassName@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E400U, 5U, 0x547E0U, "?GetTrustLevel@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIScaleAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IScaleAnimation>::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E400U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6E400U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6E400U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6E400U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6E400U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6E400U, 11U, 0x5AC80U, nullptr, nullptr, true, 0},
    {0x6E460U, 0U, 0x5C850U, nullptr, nullptr, true, 0},
    {0x6E460U, 1U, 0x5B060U, nullptr, nullptr, true, 0},
    {0x6E460U, 2U, 0x5CCE0U, nullptr, nullptr, true, 0},
    {0x6E460U, 3U, 0x5B870U, nullptr, nullptr, true, 0},
    {0x6E460U, 4U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E460U, 5U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6E460U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6E460U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6E460U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6E460U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6E460U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6E460U, 11U, 0x5AC40U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 0U, 0x5C860U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 1U, 0x5B0C0U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 2U, 0x5CD70U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E4C0U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E508U, 0U, 0x5C8A0U, nullptr, nullptr, true, 0},
    {0x6E508U, 1U, 0x5B150U, nullptr, nullptr, true, 0},
    {0x6E508U, 2U, 0x5CE30U, nullptr, nullptr, true, 0},
    {0x6E508U, 3U, 0x5C2F0U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::GetWeakReference(struct IWeakReference * *)", false, 0},
    {0x6E528U, 0U, 0x5C8B0U, nullptr, nullptr, true, 0},
    {0x6E528U, 1U, 0x5B160U, nullptr, nullptr, true, 0},
    {0x6E528U, 2U, 0x5CE40U, nullptr, nullptr, true, 0},
    {0x6E528U, 3U, 0x5B980U, nullptr, nullptr, true, 0},
    {0x6E528U, 4U, 0x5BC70U, nullptr, nullptr, true, 0},
    {0x6E528U, 5U, 0x5C030U, nullptr, nullptr, true, 0},
    {0x6E528U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E528U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E568U, 0U, 0x5C880U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E568U, 1U, 0x5B0E0U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::AddRef(void)", false, 0},
    {0x6E568U, 2U, 0x5CD90U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::Release(void)", false, 0},
    {0x6E568U, 3U, 0x5B8E0U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E568U, 4U, 0x5AEB0U, "?GetRuntimeClassName@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E568U, 5U, 0x547E0U, "?GetTrustLevel@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@VWinRTAnimationBase@@UIOpacityAnimation@AnimationMetrics@Core@UI@Windows@@@Details@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, class WinRTAnimationBase, struct Windows::UI::Core::AnimationMetrics::IOpacityAnimation>::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E568U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6E568U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6E568U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6E568U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6E568U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6E568U, 11U, 0x5AC80U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 0U, 0x5C890U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 1U, 0x5B140U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 2U, 0x5CE20U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E5C8U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E610U, 0U, 0x5C780U, nullptr, nullptr, true, 0},
    {0x6E610U, 1U, 0x5B040U, nullptr, nullptr, true, 0},
    {0x6E610U, 2U, 0x5CC10U, nullptr, nullptr, true, 0},
    {0x6E610U, 3U, 0x5B7F0U, nullptr, nullptr, true, 0},
    {0x6E610U, 4U, 0x5BC60U, nullptr, nullptr, true, 0},
    {0x6E610U, 5U, 0x5C020U, nullptr, nullptr, true, 0},
    {0x6E610U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E648U, 0U, 0x5C790U, nullptr, nullptr, true, 0},
    {0x6E648U, 1U, 0x5B050U, nullptr, nullptr, true, 0},
    {0x6E648U, 2U, 0x5CC20U, nullptr, nullptr, true, 0},
    {0x6E648U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E648U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E648U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E648U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E648U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E648U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E690U, 0U, 0x5C760U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E690U, 1U, 0x5AFD0U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::AddRef(void)", false, 0},
    {0x6E690U, 2U, 0x5CB70U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::Release(void)", false, 0},
    {0x6E690U, 3U, 0x5B770U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E690U, 4U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E690U, 5U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6E690U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E690U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E690U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E690U, 9U, 0x5BA50U, nullptr, nullptr, true, 0},
    {0x6E690U, 10U, 0x5AC00U, nullptr, nullptr, true, 0},
    {0x6E6E8U, 0U, 0x5C770U, nullptr, nullptr, true, 0},
    {0x6E6E8U, 1U, 0x5B030U, nullptr, nullptr, true, 0},
    {0x6E6E8U, 2U, 0x5CC00U, nullptr, nullptr, true, 0},
    {0x6E6E8U, 3U, 0x5C190U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::GetWeakReference(struct IWeakReference * *)", false, 0},
    {0x6E708U, 0U, 0x5C690U, nullptr, nullptr, true, 0},
    {0x6E708U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6E708U, 2U, 0x5CAA0U, nullptr, nullptr, true, 0},
    {0x6E708U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6E728U, 0U, 0x5C6A0U, nullptr, nullptr, true, 0},
    {0x6E728U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6E728U, 2U, 0x5CAB0U, nullptr, nullptr, true, 0},
    {0x6E728U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E728U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E728U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E728U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E728U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E728U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E770U, 0U, 0x5C840U, nullptr, nullptr, true, 0},
    {0x6E770U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6E770U, 2U, 0x5CCD0U, nullptr, nullptr, true, 0},
    {0x6E770U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E770U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E770U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E770U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E770U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E770U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 0U, 0x5C600U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IIterator@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E7B8U, 1U, 0x5AF50U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 2U, 0x5CA10U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IIterator@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::Release(void)", false, 0},
    {0x6E7B8U, 3U, 0x5B690U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IIterator@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E7B8U, 4U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 5U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 9U, 0x5BA40U, nullptr, nullptr, true, 0},
    {0x6E7B8U, 10U, 0x5ABC0U, nullptr, nullptr, true, 0},
    {0x6E810U, 0U, 0x5C7A0U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIAnimationDescription@AnimationMetrics@Core@UI@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E810U, 1U, 0x5AF50U, nullptr, nullptr, true, 0},
    {0x6E810U, 2U, 0x5CC30U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIAnimationDescription@AnimationMetrics@Core@UI@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::Release(void)", false, 0},
    {0x6E810U, 3U, 0x5B800U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIAnimationDescription@AnimationMetrics@Core@UI@Windows@@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::UI::Core::AnimationMetrics::IAnimationDescription, class Microsoft::WRL::FtmBase>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E810U, 4U, 0x5AEB0U, nullptr, nullptr, true, 0},
    {0x6E810U, 5U, 0x547E0U, nullptr, nullptr, true, 0},
    {0x6E810U, 6U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E810U, 7U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E810U, 8U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E810U, 9U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E810U, 10U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6E810U, 11U, 0x5ABC0U, nullptr, nullptr, true, 0},
    {0x6E870U, 0U, 0x5C830U, nullptr, nullptr, true, 0},
    {0x6E870U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6E870U, 2U, 0x5CCC0U, nullptr, nullptr, true, 0},
    {0x6E870U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6E870U, 4U, 0x59850U, nullptr, nullptr, true, 0},
    {0x6E870U, 5U, 0x5C440U, nullptr, nullptr, true, 0},
    {0x6E870U, 6U, 0x54100U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 0U, 0x5C840U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 2U, 0x5CED0U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E8B8U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E900U, 0U, 0x5C7A0U, "?QueryInterface@AnimationDescription@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl AnimationDescription::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E900U, 1U, 0x5AF50U, "?AddRef@AnimationDescription@@UEAAKXZ", "public: virtual unsigned long __cdecl AnimationDescription::AddRef(void)", false, 0},
    {0x6E900U, 2U, 0x5CEB0U, "?Release@AnimationDescription@@UEAAKXZ", "public: virtual unsigned long __cdecl AnimationDescription::Release(void)", false, 0},
    {0x6E900U, 3U, 0x5B800U, "?GetIids@AnimationDescription@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl AnimationDescription::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E900U, 4U, 0x5BC80U, "?GetRuntimeClassName@AnimationDescription@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl AnimationDescription::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E900U, 5U, 0x5C040U, "?GetTrustLevel@AnimationDescription@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl AnimationDescription::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E900U, 6U, 0x5D4E0U, "?get_Animations@AnimationDescription@@UEAAJPEAPEAU?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@@Z", "public: virtual long __cdecl AnimationDescription::get_Animations(struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *> * *)", false, 0},
    {0x6E900U, 7U, 0x5D6F0U, "?get_StaggerDelay@AnimationDescription@@UEAAJPEAUTimeSpan@Foundation@Windows@@@Z", "public: virtual long __cdecl AnimationDescription::get_StaggerDelay(struct Windows::Foundation::TimeSpan *)", false, 0},
    {0x6E900U, 8U, 0x5D710U, "?get_StaggerDelayFactor@AnimationDescription@@UEAAJPEAM@Z", "public: virtual long __cdecl AnimationDescription::get_StaggerDelayFactor(float *)", false, 0},
    {0x6E900U, 9U, 0x5D590U, "?get_DelayLimit@AnimationDescription@@UEAAJPEAUTimeSpan@Foundation@Windows@@@Z", "public: virtual long __cdecl AnimationDescription::get_DelayLimit(struct Windows::Foundation::TimeSpan *)", false, 0},
    {0x6E900U, 10U, 0x5D740U, "?get_ZOrder@AnimationDescription@@UEAAJPEAH@Z", "public: virtual long __cdecl AnimationDescription::get_ZOrder(int *)", false, 0},
    {0x6E900U, 11U, 0x5ACF0U, nullptr, nullptr, true, 0},
    {0x6E960U, 0U, 0x5C830U, nullptr, nullptr, true, 0},
    {0x6E960U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6E960U, 2U, 0x5CEC0U, nullptr, nullptr, true, 0},
    {0x6E960U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6E980U, 0U, 0x5C690U, nullptr, nullptr, true, 0},
    {0x6E980U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6E980U, 2U, 0x5CF60U, nullptr, nullptr, true, 0},
    {0x6E980U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 0U, 0x5C6A0U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 2U, 0x5CF70U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6E9A0U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6E9E8U, 0U, 0x5C600U, "?QueryInterface@WinRTAnimationVectorIterator@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6E9E8U, 1U, 0x5AF50U, "?AddRef@WinRTAnimationVectorIterator@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTAnimationVectorIterator::AddRef(void)", false, 0},
    {0x6E9E8U, 2U, 0x5CF50U, "?Release@WinRTAnimationVectorIterator@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTAnimationVectorIterator::Release(void)", false, 0},
    {0x6E9E8U, 3U, 0x5B690U, "?GetIids@WinRTAnimationVectorIterator@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6E9E8U, 4U, 0x5BD20U, "?GetRuntimeClassName@WinRTAnimationVectorIterator@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6E9E8U, 5U, 0x5C040U, "?GetTrustLevel@WinRTAnimationVectorIterator@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6E9E8U, 6U, 0x5D550U, "?get_Current@WinRTAnimationVectorIterator@@UEAAJPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::get_Current(struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *)", false, 0},
    {0x6E9E8U, 7U, 0x5D600U, "?get_HasCurrent@WinRTAnimationVectorIterator@@UEAAJPEAE@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::get_HasCurrent(unsigned char *)", false, 0},
    {0x6E9E8U, 8U, 0x5C4E0U, "?MoveNext@WinRTAnimationVectorIterator@@UEAAJPEAE@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::MoveNext(unsigned char *)", false, 0},
    {0x6E9E8U, 9U, 0x5BB30U, "?GetMany@WinRTAnimationVectorIterator@@UEAAJIPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@PEAI@Z", "public: virtual long __cdecl WinRTAnimationVectorIterator::GetMany(unsigned int, struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *, unsigned int *)", false, 0},
    {0x6E9E8U, 10U, 0x5ADB0U, nullptr, nullptr, true, 0},
    {0x6EA40U, 0U, 0x5C790U, nullptr, nullptr, true, 0},
    {0x6EA40U, 1U, 0x5B050U, nullptr, nullptr, true, 0},
    {0x6EA40U, 2U, 0x5CF40U, nullptr, nullptr, true, 0},
    {0x6EA40U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6EA40U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6EA40U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6EA40U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6EA40U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6EA40U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6EA88U, 0U, 0x5C770U, nullptr, nullptr, true, 0},
    {0x6EA88U, 1U, 0x5B030U, nullptr, nullptr, true, 0},
    {0x6EA88U, 2U, 0x5CF20U, nullptr, nullptr, true, 0},
    {0x6EA88U, 3U, 0x5C190U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@U?$IVectorView@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@U?$IIterable@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@567@VFtmBase@23@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::Foundation::Collections::IVectorView<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, struct Windows::Foundation::Collections::IIterable<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *>, class Microsoft::WRL::FtmBase>::GetWeakReference(struct IWeakReference * *)", false, 0},
    {0x6EAA8U, 0U, 0x5C780U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 1U, 0x5B040U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 2U, 0x5CF30U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 3U, 0x5B7F0U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 4U, 0x5BD10U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 5U, 0x5C060U, nullptr, nullptr, true, 0},
    {0x6EAA8U, 6U, 0x5B4F0U, "?First@WinRTAnimationVector@@UEAAJPEAPEAU?$IIterator@PEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Collections@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationVector::First(struct Windows::Foundation::Collections::IIterator<struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *> * *)", false, 0},
    {0x6EAE0U, 0U, 0x5C760U, "?QueryInterface@WinRTAnimationVector@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTAnimationVector::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6EAE0U, 1U, 0x5AFD0U, "?AddRef@WinRTAnimationVector@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTAnimationVector::AddRef(void)", false, 0},
    {0x6EAE0U, 2U, 0x5CF10U, "?Release@WinRTAnimationVector@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTAnimationVector::Release(void)", false, 0},
    {0x6EAE0U, 3U, 0x5B770U, "?GetIids@WinRTAnimationVector@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTAnimationVector::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6EAE0U, 4U, 0x5BCE0U, "?GetRuntimeClassName@WinRTAnimationVector@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTAnimationVector::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6EAE0U, 5U, 0x5C040U, "?GetTrustLevel@WinRTAnimationVector@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTAnimationVector::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6EAE0U, 6U, 0x5B570U, "?GetAt@WinRTAnimationVector@@UEAAJIPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationVector::GetAt(unsigned int, struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *)", false, 0},
    {0x6EAE0U, 7U, 0x5D6E0U, "?get_Size@WinRTAnimationVector@@UEAAJPEAI@Z", "public: virtual long __cdecl WinRTAnimationVector::get_Size(unsigned int *)", false, 0},
    {0x6EAE0U, 8U, 0x5C3A0U, "?IndexOf@WinRTAnimationVector@@UEAAJPEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@PEAIPEAE@Z", "public: virtual long __cdecl WinRTAnimationVector::IndexOf(struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation *, unsigned int *, unsigned char *)", false, 0},
    {0x6EAE0U, 9U, 0x5BA60U, "?GetMany@WinRTAnimationVector@@UEAAJIIPEAPEAUIPropertyAnimation@AnimationMetrics@Core@UI@Windows@@PEAI@Z", "public: virtual long __cdecl WinRTAnimationVector::GetMany(unsigned int, unsigned int, struct Windows::UI::Core::AnimationMetrics::IPropertyAnimation * *, unsigned int *)", false, 0},
    {0x6EAE0U, 10U, 0x5AD70U, nullptr, nullptr, true, 0},
    {0x6EB38U, 0U, 0x5C8B0U, nullptr, nullptr, true, 0},
    {0x6EB38U, 1U, 0x5B160U, nullptr, nullptr, true, 0},
    {0x6EB38U, 2U, 0x5CFB0U, nullptr, nullptr, true, 0},
    {0x6EB38U, 3U, 0x5B980U, nullptr, nullptr, true, 0},
    {0x6EB38U, 4U, 0x5BD80U, nullptr, nullptr, true, 0},
    {0x6EB38U, 5U, 0x5C070U, nullptr, nullptr, true, 0},
    {0x6EB38U, 6U, 0x5D620U, "?get_InitialOpacity@WinRTOpacityAnimation@@UEAAJPEAPEAU?$IReference@M@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTOpacityAnimation::get_InitialOpacity(struct Windows::Foundation::IReference<float> * *)", false, 0},
    {0x6EB38U, 7U, 0x5D5D0U, "?get_FinalOpacity@WinRTOpacityAnimation@@UEAAJPEAM@Z", "public: virtual long __cdecl WinRTOpacityAnimation::get_FinalOpacity(float *)", false, 0},
    {0x6EB78U, 0U, 0x5C890U, nullptr, nullptr, true, 0},
    {0x6EB78U, 1U, 0x5B140U, nullptr, nullptr, true, 0},
    {0x6EB78U, 2U, 0x5CF90U, nullptr, nullptr, true, 0},
    {0x6EB78U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6EB78U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6EB78U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6EB78U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6EB78U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6EB78U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6EBC0U, 0U, 0x5C8A0U, nullptr, nullptr, true, 0},
    {0x6EBC0U, 1U, 0x5B150U, nullptr, nullptr, true, 0},
    {0x6EBC0U, 2U, 0x5CFA0U, nullptr, nullptr, true, 0},
    {0x6EBC0U, 3U, 0x5C2F0U, nullptr, nullptr, true, 0},
    {0x6EBE0U, 0U, 0x5C870U, nullptr, nullptr, true, 0},
    {0x6EBE0U, 1U, 0x5B0D0U, nullptr, nullptr, true, 0},
    {0x6EBE0U, 2U, 0x5D010U, nullptr, nullptr, true, 0},
    {0x6EBE0U, 3U, 0x5C240U, nullptr, nullptr, true, 0},
    {0x6EC00U, 0U, 0x5C880U, "?QueryInterface@WinRTOpacityAnimation@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTOpacityAnimation::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6EC00U, 1U, 0x5B0E0U, "?AddRef@WinRTOpacityAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTOpacityAnimation::AddRef(void)", false, 0},
    {0x6EC00U, 2U, 0x5CF80U, "?Release@WinRTOpacityAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTOpacityAnimation::Release(void)", false, 0},
    {0x6EC00U, 3U, 0x5B8E0U, "?GetIids@WinRTOpacityAnimation@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTOpacityAnimation::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6EC00U, 4U, 0x5BD50U, "?GetRuntimeClassName@WinRTOpacityAnimation@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTOpacityAnimation::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6EC00U, 5U, 0x5C040U, "?GetTrustLevel@WinRTOpacityAnimation@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTOpacityAnimation::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6EC00U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6EC00U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6EC00U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6EC00U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6EC00U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6EC00U, 11U, 0x5ADF0U, nullptr, nullptr, true, 0},
    {0x6EC60U, 0U, 0x5C850U, "?QueryInterface@WinRTTranslationAnimation@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTTranslationAnimation::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6EC60U, 1U, 0x5B060U, "?AddRef@WinRTTranslationAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTTranslationAnimation::AddRef(void)", false, 0},
    {0x6EC60U, 2U, 0x5CFF0U, "?Release@WinRTTranslationAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTTranslationAnimation::Release(void)", false, 0},
    {0x6EC60U, 3U, 0x5B870U, "?GetIids@WinRTTranslationAnimation@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTTranslationAnimation::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6EC60U, 4U, 0x5BE00U, "?GetRuntimeClassName@WinRTTranslationAnimation@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTTranslationAnimation::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6EC60U, 5U, 0x5C040U, "?GetTrustLevel@WinRTTranslationAnimation@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTTranslationAnimation::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6EC60U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6EC60U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6EC60U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6EC60U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6EC60U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6EC60U, 11U, 0x5AC40U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 0U, 0x5C860U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 1U, 0x5B0C0U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 2U, 0x5D000U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6ECC0U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6ED08U, 0U, 0x5C8F0U, nullptr, nullptr, true, 0},
    {0x6ED08U, 1U, 0x5B160U, nullptr, nullptr, true, 0},
    {0x6ED08U, 2U, 0x5CFB0U, nullptr, nullptr, true, 0},
    {0x6ED08U, 3U, 0x5BA30U, nullptr, nullptr, true, 0},
    {0x6ED08U, 4U, 0x5BDF0U, nullptr, nullptr, true, 0},
    {0x6ED08U, 5U, 0x5C070U, nullptr, nullptr, true, 0},
    {0x6ED08U, 6U, 0x5D620U, "?get_InitialScaleX@WinRTScaleAnimation@@UEAAJPEAPEAU?$IReference@M@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::get_InitialScaleX(struct Windows::Foundation::IReference<float> * *)", false, 0},
    {0x6ED08U, 7U, 0x5D670U, "?get_InitialScaleY@WinRTScaleAnimation@@UEAAJPEAPEAU?$IReference@M@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::get_InitialScaleY(struct Windows::Foundation::IReference<float> * *)", false, 0},
    {0x6ED08U, 8U, 0x5D5E0U, "?get_FinalScaleX@WinRTScaleAnimation@@UEAAJPEAM@Z", "public: virtual long __cdecl WinRTScaleAnimation::get_FinalScaleX(float *)", false, 0},
    {0x6ED08U, 9U, 0x5D5F0U, "?get_FinalScaleY@WinRTScaleAnimation@@UEAAJPEAM@Z", "public: virtual long __cdecl WinRTScaleAnimation::get_FinalScaleY(float *)", false, 0},
    {0x6ED08U, 10U, 0x5D6C0U, "?get_NormalizedOrigin@WinRTScaleAnimation@@UEAAJPEAUPoint@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::get_NormalizedOrigin(struct Windows::Foundation::Point *)", false, 0},
    {0x6ED60U, 0U, 0x5C8D0U, nullptr, nullptr, true, 0},
    {0x6ED60U, 1U, 0x5B140U, nullptr, nullptr, true, 0},
    {0x6ED60U, 2U, 0x5CF90U, nullptr, nullptr, true, 0},
    {0x6ED60U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6ED60U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6ED60U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6ED60U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6ED60U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6ED60U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6EDA8U, 0U, 0x5C8E0U, nullptr, nullptr, true, 0},
    {0x6EDA8U, 1U, 0x5B150U, nullptr, nullptr, true, 0},
    {0x6EDA8U, 2U, 0x5CFA0U, nullptr, nullptr, true, 0},
    {0x6EDA8U, 3U, 0x5C2F0U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 0U, 0x5C8C0U, "?QueryInterface@WinRTScaleAnimation@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTScaleAnimation::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6EDC8U, 1U, 0x5B0E0U, "?AddRef@WinRTScaleAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTScaleAnimation::AddRef(void)", false, 0},
    {0x6EDC8U, 2U, 0x5CF80U, "?Release@WinRTScaleAnimation@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTScaleAnimation::Release(void)", false, 0},
    {0x6EDC8U, 3U, 0x5B990U, "?GetIids@WinRTScaleAnimation@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6EDC8U, 4U, 0x5BDC0U, "?GetRuntimeClassName@WinRTScaleAnimation@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6EDC8U, 5U, 0x5C040U, "?GetTrustLevel@WinRTScaleAnimation@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTScaleAnimation::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6EDC8U, 6U, 0x5D720U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 7U, 0x5D570U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 8U, 0x5D5B0U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 9U, 0x5D510U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 10U, 0x5D530U, nullptr, nullptr, true, 0},
    {0x6EDC8U, 11U, 0x5AE70U, nullptr, nullptr, true, 0},
    {0x6EE28U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EE28U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EE28U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EE28U, 3U, 0x5C080U, "?GetUnmarshalClass@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAU4@@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::GetUnmarshalClass(struct _GUID const &, void *, unsigned long, void *, unsigned long, struct _GUID *)", false, 0},
    {0x6EE28U, 4U, 0x5BBC0U, "?GetMarshalSizeMax@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAK@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::GetMarshalSizeMax(struct _GUID const &, void *, unsigned long, void *, unsigned long, unsigned long *)", false, 0},
    {0x6EE28U, 5U, 0x5C480U, "?MarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAXK2K@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::MarshalInterface(struct IStream *, struct _GUID const &, void *, unsigned long, void *, unsigned long)", false, 0},
    {0x6EE28U, 6U, 0x5D470U, "?UnmarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::UnmarshalInterface(struct IStream *, struct _GUID const &, void * *)", false, 0},
    {0x6EE28U, 7U, 0x5D020U, "?ReleaseMarshalData@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::ReleaseMarshalData(struct IStream *)", false, 0},
    {0x6EE28U, 8U, 0x5B340U, "?DisconnectObject@FtmBase@WRL@Microsoft@@UEAAJK@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::DisconnectObject(unsigned long)", false, 0},
    {0x6EE70U, 0U, 0x5C750U, nullptr, nullptr, true, 0},
    {0x6EE70U, 1U, 0x5AFC0U, nullptr, nullptr, true, 0},
    {0x6EE70U, 2U, 0x5CFE0U, nullptr, nullptr, true, 0},
    {0x6EE70U, 3U, 0x5C080U, nullptr, nullptr, true, 0},
    {0x6EE70U, 4U, 0x5BBC0U, nullptr, nullptr, true, 0},
    {0x6EE70U, 5U, 0x5C480U, nullptr, nullptr, true, 0},
    {0x6EE70U, 6U, 0x5D470U, nullptr, nullptr, true, 0},
    {0x6EE70U, 7U, 0x5D020U, nullptr, nullptr, true, 0},
    {0x6EE70U, 8U, 0x5B340U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 0U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 1U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 2U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 3U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 4U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 5U, 0x50B20U, nullptr, nullptr, true, 0},
    {0x6EEB8U, 6U, 0x5D720U, "?get_Type@WinRTAnimationBase@@UEAAJPEAW4PropertyAnimationType@AnimationMetrics@Core@UI@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationBase::get_Type(enum Windows::UI::Core::AnimationMetrics::PropertyAnimationType *)", false, 0},
    {0x6EEB8U, 7U, 0x5D570U, "?get_Delay@WinRTAnimationBase@@UEAAJPEAUTimeSpan@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationBase::get_Delay(struct Windows::Foundation::TimeSpan *)", false, 0},
    {0x6EEB8U, 8U, 0x5D5B0U, "?get_Duration@WinRTAnimationBase@@UEAAJPEAUTimeSpan@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationBase::get_Duration(struct Windows::Foundation::TimeSpan *)", false, 0},
    {0x6EEB8U, 9U, 0x5D510U, "?get_Control1@WinRTAnimationBase@@UEAAJPEAUPoint@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationBase::get_Control1(struct Windows::Foundation::Point *)", false, 0},
    {0x6EEB8U, 10U, 0x5D530U, "?get_Control2@WinRTAnimationBase@@UEAAJPEAUPoint@Foundation@Windows@@@Z", "public: virtual long __cdecl WinRTAnimationBase::get_Control2(struct Windows::Foundation::Point *)", false, 0},
    {0x6EF10U, 0U, 0x5C6B0U, "?QueryInterface@WinRTReferenceFloat@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl WinRTReferenceFloat::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0x6EF10U, 1U, 0x5AF50U, "?AddRef@WinRTReferenceFloat@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTReferenceFloat::AddRef(void)", false, 0},
    {0x6EF10U, 2U, 0x5CFC0U, "?Release@WinRTReferenceFloat@@UEAAKXZ", "public: virtual unsigned long __cdecl WinRTReferenceFloat::Release(void)", false, 0},
    {0x6EF10U, 3U, 0x5B700U, "?GetIids@WinRTReferenceFloat@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl WinRTReferenceFloat::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0x6EF10U, 4U, 0x5BD90U, "?GetRuntimeClassName@WinRTReferenceFloat@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl WinRTReferenceFloat::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0x6EF10U, 5U, 0x5C040U, "?GetTrustLevel@WinRTReferenceFloat@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl WinRTReferenceFloat::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0x6EF10U, 6U, 0x5D730U, "?get_Value@WinRTReferenceFloat@@UEAAJPEAM@Z", "public: virtual long __cdecl WinRTReferenceFloat::get_Value(float *)", false, 0},
    {0x6EF10U, 7U, 0x5AE30U, nullptr, nullptr, true, 0},
    {0x6EF50U, 0U, 0x5C740U, nullptr, nullptr, true, 0},
    {0x6EF50U, 1U, 0x5AFB0U, nullptr, nullptr, true, 0},
    {0x6EF50U, 2U, 0x5CFD0U, nullptr, nullptr, true, 0},
    {0x6EF50U, 3U, 0x5C0E0U, nullptr, nullptr, true, 0},
    {0x6EF70U, 0U, 0x49980U, "?AddRef@?$CRefObj@VCThemeMenuPopup@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuPopup>::AddRef(void)", false, 0},
    {0x6EF70U, 1U, 0x48C50U, "?Release@?$CRefObj@VCThemeMenuPopup@@@@UEAAKXZ", "public: virtual unsigned long __cdecl CRefObj<class CThemeMenuPopup>::Release(void)", false, 0},
    {0x6EF70U, 2U, 0x490F0U, nullptr, nullptr, true, 0},
    {0x6EF70U, 3U, 0x3DB10U, nullptr, nullptr, true, 0},
    {0x6EF70U, 4U, 0x3E200U, nullptr, nullptr, true, 0},
    {0x6EF98U, 0U, 0x5FF20U, nullptr, nullptr, true, 0},
    {0x6EFA0U, 0U, 0x639E0U, nullptr, nullptr, true, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
